# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 072b672ca5acc83dc58f11710041668be84664ed317d9a7e521a9717dcc715e61348be798b86cf280be1fe0c60f62674732d21924ef171732a05f7d729b4f44a

test:
  secret_key_base: f4d6c32ab77ad392e0f3023b6046e1c1522ed4238713e4f40e3e973e81d4c79d15e213724f46792f86c1e08aa2a3c787b4bc69bf6daa6350ae91ca94e3b3f561

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
